SELECT 'select * from ' || tname || ';'
FROM   tab;

SELECT *
FROM   ajaxsample;
SELECT *
FROM   board;
SELECT *
FROM   countries;
SELECT *
FROM   data_table
ORDER  BY creation_date DESC;
SELECT *
FROM   departments;
SELECT *
FROM   dept_temp;
SELECT *
FROM   employees;
SELECT *
FROM   employees_temp;
SELECT *
FROM   employee_temp;
SELECT *
FROM   emp_details_view;
SELECT *
FROM   emp_temp;
SELECT *
FROM   emp_temp1;
SELECT *
FROM   fileboard;
SELECT *
FROM   issue_info;
SELECT *
FROM   item_info;
SELECT *
FROM   jobs;
SELECT *
FROM   job_history;
SELECT *
FROM   locations;
SELECT *
FROM   login_test;
SELECT *
FROM   member_hr;
SELECT *
FROM   notice;
SELECT *
FROM   receipt_info;
SELECT *
FROM   receipt_issue_txn;
SELECT *
FROM   regions;
SELECT *
FROM   score;
SELECT *
FROM   student;
SELECT *
FROM   test_temp;
SELECT *
FROM   yedam_issue_info_v;
SELECT *
FROM   yedam_product;
SELECT *
FROM   yedam_prod_onhand;
SELECT *
FROM   yedam_prod_onhand_v;
SELECT *
FROM   yedam_prod_txn;
SELECT *
FROM   yedam_receipt_info_v;
