CREATE USER spring IDENTIFIED BY spring;

GRANT CREATE SESSION,CONNECT, RESOURCE TO spring;

GRANT SELECT, INSERT, UPDATE, DELETE ON hr.employees TO spring;

GRANT SELECT, INSERT, UPDATE, DELETE ON hr.departments TO spring;

CREATE USER yderp IDENTIFIED BY yderp;

GRANT CREATE SESSION,CONNECT, RESOURCE TO yderp;

GRANT DEBUG CONNECT SESSION TO yderp;

GRANT CREATE VIEW TO yderp;
